### PR TITLE
Instances for GHC.Generics types

### PR DESCRIPTION
**Pull request by conal**
Instances for `GHC.Generics` types

### CODE REVIEW

**Comment by conal** [comment]
Thanks for the merge. Would you like me to tweak to avoid `EmptyCase` (build failure)?

**Comment by ekmett** [comment]
I'm making a small tweak at the moment to add a few more instances (M1, K1, etc.) I'll fix that while I go past.

**Comment by ekmett** [comment]
(I need to add a base-orphans dependency on older GHCs as well to avoid an issue with the fact that these things didn't used to be Functor instances)

**Comment by conal** [comment]
Thanks for the additional instances as well. I just sync'd with your repo and ran into missing `Foldable1` and `Traversable1` instances.

**Comment by ekmett** [comment]
You'll need HEAD `semigroupoids` until I can get it on hackage. This is forcing me to clean up some things there.

**Comment by conal** [comment]
Ah, thanks. I jumped the gun here. I'm in no hurry, so I'll probably wait for the new `keys` to reach Hackage.

**Pull request merged**
